project:
  type: website
  output-dir: docs

## Website tabs
website:
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resum√©
    right:
      - icon: github
        href: https://github.com/irequena24
      - icon: linkedin
        href: https://www.linkedin.com/in/ignacio-requena-770803185/
      - icon: envelope
        href: mailto:ignaciorequena@icloud.com

## Footer
page-footer:
  left:
    - "Copyright 2025, Ignacio Requena"
  right:
    - "Made using Quarto"


format:
  html:
    theme: 
    - styles.scss
    mainfont: Raleway
    toc: false
    anchor-sections: false
    page-layout: full

editor: visual

execute:
  freeze: auto